force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vehicle Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Exterior_Color__c.field-meta.xml
<CustomField>
    <fullName>Exterior_Color__c</fullName>
    <defaultValue>&quot;Black&quot;</defaultValue>
    <label>Exterior Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Exterior_Colors</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Interior_Color__c.field-meta.xml
<CustomField>
    <fullName>Interior_Color__c</fullName>
    <defaultValue>&quot;White&quot;</defaultValue>
    <label>Interior Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vegan_White</fullName>
                <label>Vegan White</label>
            </value>
            <value>
                <fullName>Vegan_Black</fullName>
                <label>Vegan Black</label>
            </value>
            <value>
                <fullName>Vegan_Tan</fullName>
                <label>Vegan Tan</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <defaultValue>&quot;Model One&quot;</defaultValue>
    <label>Model</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <defaultValue>&quot;Standard&quot;</defaultValue>
    <label>Package</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Available&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/VIN__c.field-meta.xml
<CustomField>
    <fullName>VIN__c</fullName>
    <label>VIN</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <defaultValue>&quot;2020&quot;</defaultValue>
    <label>Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Exterior_Colors.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pearl_White</fullName>
        <label>Pearl White</label>
    </customValue>
    <customValue>
        <fullName>VIP_Black</fullName>
        <label>VIP Black</label>
    </customValue>
    <customValue>
        <fullName>Pulsar_Red</fullName>
        <label>Pulsar Red</label>
    </customValue>
    <customValue>
        <fullName>Deep_Blue</fullName>
        <label>Deep Blue</label>
    </customValue>
    <customValue>
        <fullName>Modern_Green</fullName>
        <label>Modern Green</label>
    </customValue>
    <masterLabel>Exterior Colors</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Test_VehicleTriggerHandler.cls
@isTest
private class Test_VehicleTriggerHandler {
    static List<Vehicle__c> createVehicles(Integer numberofVehicles) {
        List<Vehicle__c> vehicles = new List<Vehicle__c>();
        for (Integer i = 0; i < numberofVehicles; i++) {
            vehicles.add(
                new Vehicle__c(
                    Exterior_Color__c = 'Pulsar_Red',
                    Interior_Color__c = 'Vegan_Tan',
                    Model__c = 'Model One',
                    Status__c = 'Available',
                    Year__c = '2020',
                    Package__c = 'Standard',
                    VIN__C = 'ABCD' + i
                )
            );
        }
        insert vehicles;
        return vehicles;
    }

    @isTest
    static void testTaskCreationPositive() {
        List<Vehicle__c> lstVehicle = createVehicles(1);
        Test.startTest();
        lstVehicle[0].Status__c = 'Sold';
        update lstVehicle;
        Test.stopTest();
        List<Task> lstTasks = [SELECT Id, WhatId, OwnerId, Subject FROM Task];
        String taskSubject = String.format(
            VehicleTriggerHandler.subject,
            new List<Object>{ lstVehicle[0].Model__c }
        );
        System.assertEquals(
            1,
            lstTasks.size(),
            'Expected task record count as 1 but received ' + lstTasks.size()
        );
        System.assertEquals(
            lstVehicle[0].Id,
            lstTasks[0].WhatId,
            'Expected ' +
            lstVehicle[0].Id +
            ' but received ' +
            lstTasks[0].WhatId
        );
        System.assertEquals(
            UserInfo.getUserId(),
            lstTasks[0].OwnerId,
            'Expected ' +
            UserInfo.getUserId() +
            ' but received ' +
            lstTasks[0].OwnerId
        );
        System.assertEquals(
            taskSubject,
            lstTasks[0].Subject,
            'Expected ' +
            taskSubject +
            ' but received ' +
            lstTasks[0].Subject
        );
    }
    @isTest
    static void testTaskCreationNegative() {
        List<Vehicle__c> lstVehicle = createVehicles(1);
        Test.startTest();
        lstVehicle[0].Status__c = 'On Hold';
        update lstVehicle;
        Test.stopTest();
        List<Task> lstTasks = [SELECT Id, WhatId, OwnerId, Subject FROM Task];
        System.assertEquals(
            0,
            lstTasks.size(),
            'Expected task record count as 1 but received ' + lstTasks.size()
        );
    }

    @isTest
    static void testBulkTaskCreation() {
        Map<Id, Vehicle__c> vehicleMap = new Map<Id, Vehicle__c>();
        List<Vehicle__c> lstVehicle = createVehicles(200);
        Test.startTest();
        for (Vehicle__c vehicle : lstVehicle) {
            vehicleMap.put(vehicle.Id, vehicle);
            vehicle.Status__c = 'Sold';
        }
        update lstVehicle;
        Test.stopTest();
        List<Task> lstTasks = [SELECT Id, WhatId, OwnerId, Subject FROM Task];
        System.assertEquals(
            lstVehicle.size(),
            lstTasks.size(),
            'Expected task record count as ' +
            lstVehicle.size() +
            'but received ' +
            lstTasks.size()
        );
        for (Task task : lstTasks) {
            String taskSubject = String.format(
                VehicleTriggerHandler.subject,
                new List<Object>{ vehicleMap.get(task.WhatId).Model__c }
            );
            System.assertEquals(
                vehicleMap.get(task.WhatId).Id,
                task.WhatId,
                'Expected ' +
                vehicleMap.get(task.WhatId).Id +
                ' but received ' +
                task.WhatId
            );
            System.assertEquals(
                UserInfo.getUserId(),
                task.OwnerId,
                'Expected ' +
                UserInfo.getUserId() +
                ' but received ' +
                task.OwnerId
            );
            System.assertEquals(
                taskSubject,
                task.Subject,
                'Expected ' +
                taskSubject +
                ' but received ' +
                task.Subject
            );
        }
    }
}