force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vehicle Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <defaultValue>&quot;Model One&quot;</defaultValue>
    <label>Model</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Available&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VehicleTriggerHandler.cls
public inherited sharing class VehicleTriggerHandler extends TriggerHandler {
    @TestVisible
    private static String subject = 'The vehicle {0} is sold. Call your Sales Director';

    private List<Vehicle__c> triggerNew;
    private List<Vehicle__c> triggerOld;
    private Map<Id, Vehicle__c> triggerMapNew;
    private Map<Id, Vehicle__c> triggerMapOld;

    public VehicleTriggerHandler() {
        this.triggerOld = (List<Vehicle__c>) Trigger.old;
        this.triggerNew = (List<Vehicle__c>) Trigger.new;
        this.triggerMapNew = (Map<Id, Vehicle__c>) Trigger.newMap;
        this.triggerMapOld = (Map<Id, Vehicle__c>) Trigger.oldMap;
    }

    public override void afterUpdate() {
        List<Task> newTasks = new List<Task>();
        for (Vehicle__c vehicle : triggerNew) {
            if (vehicle.Status__c != triggerMapOld.get(vehicle.Id).Status__c) {
                if (vehicle.Status__c == 'Sold') {
                    Task task = new Task();
                    task.WhatId = vehicle.Id;
                    task.OwnerId = UserInfo.getUserId();
                    task.Subject = String.format(
                        subject,
                        new List<Object>{ vehicle.Model__c }
                    );
                    newTasks.add(task);
                }
            }
        }
        try {
            insert newTasks;
        } catch (exception ex) {
            for (Vehicle__c vehicle : triggerNew) {
                vehicle.addError(
                    'Task Creation Failed with error' + ex.getMessage()
                );
            }
        }
    }
}