force-app/main/default/objects/DeliveryWaypoint__c/DeliveryWaypoint__c.object-meta.xml
<CustomObject>
    <label>Delivery Waypoint</label>
    <nameField>
        <displayFormat>DW-{00000000}</displayFormat>
        <label>Delivery Waypoint Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Waypoints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryWaypoint__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Number</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DeliveryWaypoint__c/fields/Vehicle_Order__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Order</label>
    <referenceTo>Vehicle_Order__c</referenceTo>
    <relationshipLabel>Delivery Waypoints</relationshipLabel>
    <relationshipName>Delivery_Waypoints</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Order__c/Vehicle_Order__c.object-meta.xml
<CustomObject>
    <label>Vehicle Order</label>
    <nameField>
        <displayFormat>VO-{00000}</displayFormat>
        <label>Vehicle Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Vehicle Orders</relationshipLabel>
    <relationshipName>Vehicle_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Order__c/fields/Service_Address__c.field-meta.xml
<CustomField>
    <fullName>Service_Address__c</fullName>
    <label>Service Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DeliveryRouteController.cls
public with sharing class DeliveryRouteController {
    @AuraEnabled
    public static List<DeliveryWaypoint__c> getWaypoints(Id recordId) {
        try {
            functions.Function fn = functions.Function.get(
                'ecars.routeplanner'
            );
            functions.FunctionInvocation invocation = fn.invoke(
                '{ "deliveryVehicleId": "' +
                recordId +
                '" }'
            );

            // Check if there is any error during the invocation
            if (
                invocation.getStatus() ==
                functions.FunctionInvocationStatus.ERROR
            ) {
                String errorMessage = invocation.getError() != null
                    ? invocation.getError().getMessage()
                    : 'UNKNOWN';
                System.debug(errorMessage);
                throw new CalloutException(errorMessage);
            }

            String response = invocation.getResponse();
            Slack_SendDeliveryNotification.sendDeliveryNotification(recordId);
            return [
                SELECT
                    Name,
                    Vehicle_Order__r.Name,
                    Vehicle_Order__r.Service_Location__Latitude__s,
                    Vehicle_Order__r.Service_Location__Longitude__s,
                    Vehicle_Order__r.Customer__r.Name,
                    Vehicle_Order__r.Service_Address__c,
                    Number__c
                FROM DeliveryWaypoint__c
                ORDER BY CreatedDate DESC
                LIMIT 5
            ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}