force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Configuration__c/Car_Configuration__c.object-meta.xml
<CustomObject>
    <label>Configuration</label>
    <nameField>
        <displayFormat>CFG-{000000}</displayFormat>
        <label>Car Configuration Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Car Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Configuration__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Car Model</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Car Configurations</relationshipLabel>
    <relationshipName>Car_Configurations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car_Configuration__c/fields/Vehicle_Order__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Order</label>
    <referenceTo>Vehicle_Order__c</referenceTo>
    <relationshipLabel>Car Configurations</relationshipLabel>
    <relationshipName>Car_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car_Options__c/Car_Options__c.object-meta.xml
<CustomObject>
    <label>Car Options</label>
    <nameField>
        <displayFormat>OPT-{000000}</displayFormat>
        <label>Car Options Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Car Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Options__c/fields/Car_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Car_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Car Configuration</label>
    <referenceTo>Car_Configuration__c</referenceTo>
    <relationshipLabel>Car Options</relationshipLabel>
    <relationshipName>Car_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car_Options__c/fields/Exterior_Color__c.field-meta.xml
<CustomField>
    <fullName>Exterior_Color__c</fullName>
    <label>Exterior Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pearl_White</fullName>
                <label>Pearl White</label>
            </value>
            <value>
                <fullName>VIP_Black</fullName>
                <label>VIP Black</label>
            </value>
            <value>
                <fullName>Pulsar_Red</fullName>
                <label>Pulsar Red</label>
            </value>
            <value>
                <fullName>Deep_Blue</fullName>
                <label>Deep Blue</label>
            </value>
            <value>
                <fullName>Modern_Green</fullName>
                <label>Modern Green</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car_Options__c/fields/Interior_Color__c.field-meta.xml
<CustomField>
    <fullName>Interior_Color__c</fullName>
    <label>Interior Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vegan_White</fullName>
                <label>Vegan White</label>
            </value>
            <value>
                <fullName>Vegan_Black</fullName>
                <label>Vegan Black</label>
            </value>
            <value>
                <fullName>Vegan_Tan</fullName>
                <label>Vegan Tan</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car_Options__c/fields/Range__c.field-meta.xml
<CustomField>
    <fullName>Range__c</fullName>
    <label>Range</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Short_Range</fullName>
                <label>Short Range</label>
            </value>
            <value>
                <fullName>Long_Range</fullName>
                <label>Long Range</label>
            </value>
            <value>
                <fullName>Medium_Range</fullName>
                <label>Medium Range</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Order__c/Vehicle_Order__c.object-meta.xml
<CustomObject>
    <label>Vehicle Order</label>
    <nameField>
        <displayFormat>VO-{00000}</displayFormat>
        <label>Vehicle Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Order__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration</label>
    <referenceTo>Car_Configuration__c</referenceTo>
    <relationshipLabel>Vehicle Orders</relationshipLabel>
    <relationshipName>Vehicle_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_CarOptionsController.cls
@isTest
public class Test_CarOptionsController {
    @testSetup
    static void setup() {
        Car__c car = new Car__c();
        insert car;

        Car_Configuration__c configuration = new Car_Configuration__c(
            Car__c = car.Id
        );
        insert configuration;

        Car_Options__c options = new Car_Options__c(
            Car_Configuration__c = configuration.Id,
            Range__c = 'Long_Range',
            Exterior_Color__c = 'VIP_Black',
            Interior_Color__c = 'Vegan_Tan'
        );

        insert options;

        Vehicle_Order__c order = new Vehicle_Order__c(
            Configuration__c = configuration.Id
        );
        insert order;
    }

    @isTest
    static void testGetCarOptions() {
        Test.startTest();

        Car_Configuration__c testCarConfiguration = [
            SELECT Id
            FROM Car_Configuration__c
        ];
        Car_Options__c options = CarOptionsController.getCarOptions(
            testCarConfiguration.Id
        );

        Test.stopTest();

        System.assertEquals(options.Range__c, 'Long Range');
        System.assertEquals(options.Exterior_Color__c, 'VIP Black');
        System.assertEquals(options.Interior_Color__c, 'Vegan Tan');
    }

    @isTest
    static void testGetOrderCarOptions() {
        Test.startTest();

        Vehicle_Order__c order = [SELECT Id FROM Vehicle_Order__c];

        Car_Options__c options = CarOptionsController.getOrderCarOptions(
            order.Id
        );

        Test.stopTest();

        System.assertEquals(options.Range__c, 'Long Range');
        System.assertEquals(options.Exterior_Color__c, 'VIP Black');
        System.assertEquals(options.Interior_Color__c, 'Vegan Tan');
    }
}