force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Available_Exterior_Colors__c.field-meta.xml
<CustomField>
    <fullName>Available_Exterior_Colors__c</fullName>
    <label>Available Exterior Colors</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Exterior_Colors</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/fields/Available_Interior_Colors__c.field-meta.xml
<CustomField>
    <fullName>Available_Interior_Colors__c</fullName>
    <label>Available Interior Colors</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Interior_Colors</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/fields/Available_Ranges__c.field-meta.xml
<CustomField>
    <fullName>Available_Ranges__c</fullName>
    <label>Available Ranges</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Range_Options</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/fields/Base_Price__c.field-meta.xml
<CustomField>
    <fullName>Base_Price__c</fullName>
    <label>Base Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/Exterior_Colors.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pearl_White</fullName>
        <label>Pearl White</label>
    </customValue>
    <customValue>
        <fullName>VIP_Black</fullName>
        <label>VIP Black</label>
    </customValue>
    <customValue>
        <fullName>Pulsar_Red</fullName>
        <label>Pulsar Red</label>
    </customValue>
    <customValue>
        <fullName>Deep_Blue</fullName>
        <label>Deep Blue</label>
    </customValue>
    <customValue>
        <fullName>Modern_Green</fullName>
        <label>Modern Green</label>
    </customValue>
    <masterLabel>Exterior Colors</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Interior_Colors.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Vegan_White</fullName>
        <label>Vegan White</label>
    </customValue>
    <customValue>
        <fullName>Vegan_Black</fullName>
        <label>Vegan Black</label>
    </customValue>
    <customValue>
        <fullName>Vegan_Tan</fullName>
        <label>Vegan Tan</label>
    </customValue>
    <masterLabel>Interior Colors</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Range_Options.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Short_Range</fullName>
        <label>Short Range</label>
    </customValue>
    <customValue>
        <fullName>Medium_Range</fullName>
        <label>Medium Range</label>
    </customValue>
    <customValue>
        <fullName>Long_Range</fullName>
        <label>Long Range</label>
    </customValue>
    <masterLabel>Range Options</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CarConfigurationController.cls
public with sharing class CarConfigurationController {
    @AuraEnabled(cacheable=true)
    public static CarOptionWrapper getAvailableCarOptions(String modelName) {
        try {
            CarOptionWrapper coWrapper = new CarOptionWrapper();
            Map<String, List<CarOption>> allOptions = new Map<String, List<CarOption>>();
            Car__c model = [
                SELECT
                    Id,
                    toLabel(Available_Exterior_Colors__c),
                    toLabel(Available_Interior_Colors__c),
                    toLabel(Available_Ranges__c),
                    Base_Price__c
                FROM Car__c
                WHERE Name = :modelName
                LIMIT 1
            ];
            if (model.Available_Exterior_Colors__c != null) {
                List<CarOption> options = new List<CarOption>();
                Integer addOnPrice = 0;
                for (String s : model.Available_Exterior_Colors__c.split(';')) {
                    CarOption co = new CarOption();
                    co.label = s;
                    co.addOnprice = addOnPrice;
                    co.code = co.label.split(' ')[1].toLowerCase();
                    options.add(co);
                    addOnPrice += 1000;
                }
                allOptions.put('ExteriorColors', options);
            }
            if (model.Available_Interior_Colors__c != null) {
                List<CarOption> options = new List<CarOption>();
                Integer addOnPrice = 0;
                for (String s : model.Available_Interior_Colors__c.split(';')) {
                    CarOption co = new CarOption();
                    co.label = s;
                    co.addOnprice = addOnPrice;
                    co.code = co.label.split(' ')[1].toLowerCase();
                    options.add(co);
                    addOnPrice += 1000;
                }
                allOptions.put('InteriorColors', options);
            }
            if (model.Available_Ranges__c != null) {
                List<CarOption> options = new List<CarOption>();
                Decimal addOnPrice = model.Base_Price__c;
                for (String s : model.Available_Ranges__c.split(';')) {
                    CarOption co = new CarOption();
                    co.label = s;
                    co.addOnprice = addOnPrice;
                    co.code = co.label.split(' ')[0].toLowerCase();
                    options.add(co);
                    addOnPrice += 10000;
                }
                allOptions.put('RangeOptions', options);
            }
            coWrapper.recordId = model.Id;
            coWrapper.allOptions = allOptions;
            return coWrapper;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public class CarOptionWrapper {
        @AuraEnabled
        public String recordId;
        @AuraEnabled
        public Map<String, List<CarOption>> allOptions;
    }

    public class CarOption {
        @AuraEnabled
        public String label;
        @AuraEnabled
        public Decimal addOnprice;
        @AuraEnabled
        public String code;
    }
}